apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: chuo-demo
    appstudio.openshift.io/component: e2e-tests-hmbv
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: e2e-tests-hmbv
  namespace: qe-chuo-tenant
spec:
  url: https://github.com/cuipinghuo/e2e-tests
