apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-hmbv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-hmbv
    app.kubernetes.io/part-of: chuo-demo
  name: e2e-tests-hmbv
  namespace: qe-chuo-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-hmbv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-hmbv
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:qe-chuo-tenant-e2e-tests-hmbv
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
